name: iOS Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-26

    steps:
      - name: Check Xcode version
        run: |
          xcodebuild -version
          xcodebuild -showsdks

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
        with:
          project: MediStock.xcodeproj
          scheme: MediStock
          destination: 'platform=iOS Simulator,name=iPhone 16,OS=18.6,arch=arm64'
          action: test
          result-bundle-path: 'TestResults/TestResults.xcresult'
          build-settings: |
            CODE_SIGNING_REQUIRED=NO
            CODE_SIGNING_ALLOWED=NO
            CODE_SIGN_IDENTITY=""
